/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaProg_TestSound */

#ifndef _Included_JavaProg_TestSound
#define _Included_JavaProg_TestSound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaProg_TestSound
 * Method:    getKey
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_JavaProg_TestSound_getKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
